module.exports = {
    timezone: "Europe/Madrid",
    coingeckoBaseUrl: "https://api.coingecko.com/api/v3",
    currencyParam: "eur",
    helloMessageText: "\n\nEscribe la barra / para ver en qué te puedo ayudar.\n\nAñade tus criptomonedas y recibe el valor total de tu cartera usando el API de Coingecko.\n\nMás información: https://github.com/ArtCC/cryptoinfobot-artcc\n\n",
    cancelText: "Cancelar",
    deleteText: "¿Qué criptomoneda quieres borrar de tu cartera?",
    infoPriceText: "Puedes consultar el listado de criptomonedas disponibles en https://www.coingecko.com/es",
    errorText: "¡Vaya! Parece que ha habido un problema con tu solicitud. Inténtalo de nuevo por favor.",
    notificationsTitleText: "¿Quieres activar las notificaciones automáticas del valor de tu cartera?",
    enabledNotificationsText: "Activar",
    disabledNotificationsText: "Desactivar",
    enabledNotificationsMessageText: "He activado las notificaciones para darte el valor de tu cartera de forma automática (08h - 15h - 21h).",
    disabledNotificationsMessageText: "He desactivado las notificaciones.",
    statusEnabledNotificationsText: "Ya tienes activadas las notificaciones en este chat.",
    statusEnabledAlertText: "Ya tienes activadas las alertas de precio para esta criptomoneda en este chat.",
    enabledAlertText: "He activado la alerta correctamente.",
    disabledAlertText: "He borrado la alerta correctamente.",
    emptyAlertText: "No tienes ninguna alerta de precios añadida actualmente. Puedes añadirlas por ejemplo con /alerta ethereum 3500",
    noText: "De acuerdo.",
    tokenError: "El token es incorrecto.",
    amountText: "Importe",
    totalText: "Total",
    paymentTitleText: "Gracias por apoyar el proyecto",
    paymentDescriptionText: "Con tu apoyo económico podremos mejorar el servidor donde se aloja el bot para que más usuarios puedan utilizarlo y dar más funcionalidad al mismo para que sea el mejor bot de Telegram sobre criptomonedas y tu cartera.",
    paymentPayloadText: "cryptoinfobot-artcc",
    paymentStartParameterText: "",
    paymentCurrencyText: "EUR",
    paymentPriceLabelText: "Donación",
    coinPaymentTitleText: "Gracias por apoyar el proyecto. ¿Cuánto quieres donar?",
    oneCoinText: "1 €",
    threeCoinText: "3 €",
    fiveCoinText: "5 €"
};